### ISSUE TITLE
Broken Instructions

### ISSUE THREAD

**Issue by Rudi9719** [masterking32/WoWSimpleRegistration#1]
Tried to deploy to an Ubuntu 18.04 server, had a lot more setup to do only to be thrown PHP errors. Are there more detailed compile instructions?

**Comment by masoudr** [comment]
Install PHP, Apache, MySQL [instructions](https://www.howtoforge.com/tutorial/install-apache-with-php-and-mysql-on-ubuntu-18-04-lamp/)

Script installation [instructions](https://github.com/masterking32/WoWSimpleRegistration#installation).

Enable debug mode in the config file to display errors.
https://github.com/masterking32/WoWSimpleRegistration/blob/9fb3111c435ba5d05bf6b31bea03644992c39c59/application/config/config.php.sample#L25

If you got any error, send here.

**Comment by masterking32** [comment]
Issue closed.
If you have any problem, open it again.

**Comment by Nocty1501** [comment]
I also tried to deploy this on an Ubuntu 18.04 server, and these instructions are extremely unclear. Simply installing the repo into /var/www/html doesn't work, website fails to handle request. Turning on debug mode gives the following error:
`Fatal error: Uncaught InvalidArgumentException: Unsupported PDO driver: mysql in /var/www/html/application/vendor/catfan/medoo/src/Medoo.php:280 Stack trace: #0 /var/www/html/application/include/database.php(26): Medoo\Medoo->__construct(Array) #1 /var/www/html/application/loader.php(43): database::db_connect() #2 /var/www/html/index.php(9): require_once('/var/www/html/a...') #3 {main} thrown in /var/www/html/application/vendor/catfan/medoo/src/Medoo.php on line 280`

**Comment by masterking32** [comment]
https://packages.ubuntu.com/bionic/php7.2-pdo-mysql
