### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by ArronHoltzhausen** [masterking32/WoWSimpleRegistration#10]
`FROM php:7.2-alpine3.11`
`RUN apk update && apk add build-base`
`RUN apk add postgresql postgresql-dev \`
`&&  apk add  libpng-dev \`
`&&  apk add freetype-dev \`
`&&  apk add libmcrypt-dev \`
`&&  apk add libpng-dev \`
`&&  apk add libjpeg-turbo \`
`&&  apk add libjpeg-turbo-dev  `
`RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \`
`  && docker-php-ext-install mysqli pdo pdo_mysql \`
`  && docker-php-ext-install pdo pdo_pgsql pgsql \ `
`  && docker-php-ext-configure gd \`
`        --with-freetype-dir=/usr/include/ \`
`        --with-png-dir=/usr/include \`
`        --with-jpeg-dir=/usr/include \`
`    && docker-php-ext-install gd \`
`    && docker-php-ext-install mbstring \`
`    && docker-php-ext-enable gd`
`RUN apk add zlib-dev git zip \`
`  && docker-php-ext-install zip`
`RUN curl -sS https://getcomposer.org/installer | php \`
       ` && mv composer.phar /usr/local/bin/ \`
        `&& ln -s /usr/local/bin/composer.phar /usr/local/bin/composer`
`COPY . /home/www-data`
`WORKDIR /home/www-data/application`
`RUN composer update && composer install --prefer-source --no-interaction`
`WORKDIR /home/www-data/`
`ENV PATH="~/.composer/vendor/bin:./vendor/bin:${PATH}"`
`EXPOSE 8000`
`EXPOSE 587`
`EXPOSE 3306`
`ENTRYPOINT php -S 0.0.0.0:8000`

took the time to make a Dockerfile for you, could not submit a PR tho. 
example use case of the dockerfile

docker build . -t wowsignup:dev
docker run -d -p 80:8000 --name=wowsignup wowsignup:dev

**Comment by masterking32** [comment]
@ArronHoltzhausen We need the soap too!

**Comment by ArronHoltzhausen** [comment]
add it?

**Comment by masterking32** [comment]
Yes, If you can yes and test the project with your Docker, I cannot use the Docker.
Give me feedback then I will add your code to the project, Thank you.
