### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by 171497767** [masterking32/WoWSimpleRegistration#100]
tc 10.x

mysql 8.0.3

php 8.0.2

Warning: Undefined array key "username" in D:\xxx\WWW\WoWSimpleRegistration\application\include\user.php on line 127

**Comment by TheSCREWEDSoftware** [comment]
> tc 10.x
> 
> mysql 8.0.3
> 
> php 8.0.2
> 
> Warning: Undefined array key "username" in D:\xxx\WWW\WoWSimpleRegistration\application\include\user.php on line 127

1) Are you using supported characters for the user? 2) I pressume you have the Bnet auth enabled? TrinityCore is what exp?

**Comment by leapyear1969** [comment]
same happens here:

Warning: Undefined array key "username" in /var/www/legion/application/include/user.php on line 127

it looks like the *application/vendor/catfan/medoo/src/Medoo.php* in higher version like php 8 cannot have a good deal withe mysql
