### ISSUE TITLE
SRP mismatch

### ISSUE THREAD

**Issue by funjoker** [masterking32/WoWSimpleRegistration#106]
**Is your feature request related to a problem? Please describe.**
Site does not support newer wow SRP (e.g. TrinityCore master, cata_classic)

**Describe the solution you'd like**
Add support for newer wow SRP version supporting TWW and Cata Classic

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by masterking32** [comment]
Hello, Are you talking about SRP6?
https://github.com/masterking32/WoWSimpleRegistration/blob/266687206ba94a87d20b7f6efeeae84baad05d6a/application/config/config.php.sample#L66

**Comment by funjoker** [comment]
https://github.com/TrinityCore/TrinityCore/commit/623202d68e862b346b22ac65f9dcbb498d2fa2ac

SRPv2

**Comment by masterking32** [comment]
Ok then If you are working, I will wait for you. Thanks.
