### ISSUE TITLE
Register as link

### ISSUE THREAD

**Issue by al3xc1985** [masterking32/WoWSimpleRegistration#11]
so I am trying to link the register page but I can't, cause register page is not a link
  Example :First of all, you must <a href="http://orderofsilverhand.servegame.com/" target="_blank">create an account</a>.  

But I can't link it cause it doesn't hage a link! can you help or implement something about it?

**Comment by masterking32** [comment]
URL not available.
This project is one page and you cannot do that ... but you can try this: http://you.com/index.php#register

You can create register page,
Create a copy from index.php to register.php
Change `require_once base_path . 'template/' . get_config('template') . '/tpl/main.php';` to `require_once base_path . 'template/' . get_config('template') . '/tpl/register.php';` in register.php file.
Then go to your template folder.
Create a copy from main.php as register.php.
Then remove everything and just keep the registration section.
Now open the website like this: you.com/register.php
(Maybe you need edit header.php and footer.php too!)

**Comment by al3xc1985** [comment]
if I delete all the everything except the register part the site won;t work the same anymore... I mean the other links will not work anymore... contactus, howtoconnect, etc... I must click on home back to I can get back to those @masterking32
