### ISSUE TITLE
vote system

### ISSUE THREAD

**Issue by al3xc1985** [masterking32/WoWSimpleRegistration#12]
for cmangos users vote system is not available?>
I don't know how to activate it, make it show up link a link on my site or something...

I am using kaelthas template...

**Comment by masterking32** [comment]
That must work,
Check this:
https://github.com/masterking32/WoWSimpleRegistration/blob/master/application/config/config.php.sample#L89

**Comment by al3xc1985** [comment]
working thankyou ...can be closed

**Comment by al3xc1985** [comment]
I can say that advance template is way nicer than any others
