### ISSUE TITLE
Vote problems

### ISSUE THREAD

**Issue by al3xc1985** [masterking32/WoWSimpleRegistration#14]
ok so, I setup the vote links and image adresses, and when I click on them, the site on refreshes himself and nothing in rest..

Would be usefull to implement new tab feature... I mean when you click on the vote link to open the vote page in a new tab

**Comment by masterking32** [comment]
https://github.com/masterking32/WoWSimpleRegistration/commit/249dfae375a994c35c7318a368257ea66cbee66e
