### ISSUE TITLE
Create account via SOAP expansion config

### ISSUE THREAD

**Issue by al3xc1985** [masterking32/WoWSimpleRegistration#17]
I can create account via soap, but by default accounts are created with expansion 0 set...
I have $config['expansion'] = '1';    in config.php... but is not creating accounts with expansion 1... what can be done to create accounts with different valor to expansion?

**Comment by Ansem** [comment]
Set the default value for the SQL entry expansion to 1 (no editing to this script needed)
Or edit the code so that it runs a second game "account set addon <username> 1" after registering.
Masterking will likely know a much better and cleaner solution, but it can hopefully give you a temporary solution until then.

**Comment by al3xc1985** [comment]
thank you

**Comment by masterking32** [comment]
Hmmm, sorry I forget that I will add a new commit about this, Thanks for report.

**Comment by al3xc1985** [comment]
until @masterking32 do a commit with that config..I did something simplier
in config.php I added "1" at the end of the command:
'account create {USERNAME} {PASSWORD} 1'
because the command has in server incorporate the expansion set value, after username and password...
you can put 2 for wotlk, 3 for cata...and so on

**Comment by masterking32** [comment]
So I don't need to do something :D Thank you.

**Comment by al3xc1985** [comment]
well @masterking32 you still need to do something, because ppl won't know how to fix this problem... at least add a comment on top of that line with this stuff... and add 0 by default in config file..
