### ISSUE TITLE
Error data base acess

### ISSUE THREAD

**Issue by alexsanderds** [masterking32/WoWSimpleRegistration#18]
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /var/www/html/brasil-wow/application/vendor/catfan/medoo/src/Medoo.php:323 Stack trace: #0 /var/www/html/brasil-wow/application/include/database.php(39): Medoo\Medoo->__construct() #1 /var/www/html/brasil-wow/application/loader.php(48): database::db_connect() #2 /var/www/html/brasil-wow/index.php(33): require_once('/var/www/html/b...') #3 {main} thrown in /var/www/html/brasil-wow/application/vendor/catfan/medoo/src/Medoo.php on line 323

everything I do, is the same error
I'm using the debian 10 buster, MariaDB 10

  | Nome do Utilizador | Nome do Host | Tipo | Privilégios | Conceder/Grant | Acções
-- | -- | -- | -- | -- | -- | --
  | root | % | global | ALL PRIVILEGES | Sim | Editar privilégios | Exportar
  | root | localhost | global | ALL PRIVILEGES | Sim | Editar privilégios | Exportar
  | wowadmin | % | global | ALL PRIVILEGES | Sim | Editar privilégios | Exportar
  | wowadmin | localhost | global | ALL PRIVILEGES | Sim

Could you help me, please

**Comment by masterking32** [comment]
Hey,
[Try this](https://stackoverflow.com/questions/45293030/sqlstatehy000-1045-access-denied-for-userlocalhost-using-password-yes)
