### ISSUE TITLE
Unclear Installation Instructions

### ISSUE THREAD

**Issue by Nocty1501** [masterking32/WoWSimpleRegistration#2]
I tried to deploy this on an Ubuntu 18.04 server, and the instructions are extremely unclear. Simply installing the repo into /var/www/html doesn't work, website fails to handle request. Turning on debug mode gives the following error:
`Fatal error: Uncaught InvalidArgumentException: Unsupported PDO driver: mysql in /var/www/html/application/vendor/catfan/medoo/src/Medoo.php:280 Stack trace: #0 /var/www/html/application/include/database.php(26): Medoo\Medoo->__construct(Array) #1 /var/www/html/application/loader.php(43): database::db_connect() #2 /var/www/html/index.php(9): require_once('/var/www/html/a...') #3 {main} thrown in /var/www/html/application/vendor/catfan/medoo/src/Medoo.php on line 280`

**Comment by Nocty1501** [comment]
Silly me forgot to install php-mysql. New errors now, but related to the config. Apologies for any confusion.

**Comment by masterking32** [comment]
https://www.digitalocean.com/community/questions/i-need-to-enable-pdo-mysql-in-digital-ocean-ubuntu-16-04-server-on-my-php-7-1
