### ISSUE TITLE
2fa qr code scanning not working on iphone

### ISSUE THREAD

**Issue by locus313** [masterking32/WoWSimpleRegistration#21]
When i tried to scan one of the generated qr codes on my iphone i got the following error:
<img src="https://user-images.githubusercontent.com/4015312/89134871-80ae7800-d4dd-11ea-9761-2fa0e73fd028.png" width="350" height="243">

Doing some research it looks like the 2fa key needs to be base32 encoded for the scanning to work.

Is that something you can add?

**Comment by locus313** [comment]
I was actually able to get this working.

I added two new dependencies:
https://github.com/locus313/WoWSimpleRegistration/commit/e5f1f77f2a36e81ce0831a492db51222b9b5c154
https://github.com/locus313/WoWSimpleRegistration/commit/1e601a81d9579d6d97c59623e4f00a1346b4ca36

then modified the user.php:
https://github.com/locus313/WoWSimpleRegistration/commit/657e1e55a463701dabe7fca07366ef3eff93f049

I am using azerothcore, there is not currently a command to set the 2fa that i can see. So the soap option wasn't working for me. So had to update it directly in the database.

Then i update the uri formating so it show up a little nicer in other google authenticator compliant apps (like lastpass authenticator);
https://github.com/locus313/WoWSimpleRegistration/commit/8e9b0d6cadce055e50c1508e32f92be5fe1d6144

when i was looking at the uri formatting here:
https://github.com/google/google-authenticator/wiki/Key-Uri-Format
the issuer parameter was also strongly recommended. 

Also something else i found during my testing, if you have spaces in your page title, It will cause the uri format to be invalid.

**Comment by masterking32** [comment]
That's work with code?
Maybe the issue is about server name!

**Comment by locus313** [comment]
The code updates i made are working for me. I did have to make sure the base32 encoded secret was used to store in the azerothcore databse. You can see in this file where azerothcore is decoding the secret that gets stored in the database:
https://github.com/azerothcore/azerothcore-wotlk/blob/de586fa53f7db405f27de1ceaf0a76fb58d3924f/src/server/authserver/Server/TOTP.cpp

Also the code to manually add the secret to google authenticator also needs to be base32 encoded. otherwise you will just get a similar error to what i got above. I did change the page title to not include any spaces to make sure that was not the issue.

**Comment by masterking32** [comment]
So, you just need to use `base64_encode($tfa_key)` for insert.

**Comment by locus313** [comment]
actually that wont work ether, as google authenticator has issues with "=" padding that gets added at the end (atleast for ios devices). This is why i added paragonie/constant_time_encoding so i could use the Base32::encodeUpperUnpadded function. This makes it so there is no padding in the secrets that get generated. You can see the post here that talks about the issue:
https://stackoverflow.com/questions/49233459/invalid-barcode-google-authenticator-ios-padding-with

The url and key sent in the email also need to be base32 encoded other wise google authenticator will see it as invalid (atleast on ios).

**Comment by masterking32** [comment]
If you say, AzerothCore required based64, just use base64_encode for database, don't update `$tfa_key` variable.
Example:
```
$database_field = base64_encode($tfa_key);
```
Use `$database_field` for update database.

**Comment by locus313** [comment]
In my case i have it working using the following code:

`$ga = new PHPGangsta_GoogleAuthenticator();`
`$tfa_key = $ga->createSecret();`
`$tfa_secret = Base32::encodeUpperUnpadded($tfa_key);`

`database::$auth->update('account', [`
`            'token_key' => $antiXss->xss_clean($tfa_secret)`
`        ], [`
`            'id[=]' => $userinfo['id']`
`        ]);`


`$message .= '<img src="https://api.qrserver.com/v1/create-qr-code/?data=otpauth://totp/'. get_config('page_title') . ':' . $acc_name . '?secret=' . $tfa_secret . '&issuer=' . get_config('page_title') . '&size=200x200&ecc=M"><BR>';`
`$message .= 'or you can add this code to Google Authenticator: <B>' . $tfa_secret . '</B>.<BR>';`

I have verified using ios scanning of the qr code and manually entering the base32 encoded key works and i am able to authenticate to azerothcore. if you don't encode the the created secret the ios Google Authenticator will say its an invalid code. (at least in my testing)

**Comment by masterking32** [comment]
database::$auth->update('account', [
$database_field = base64_encode($tfa_key);'token_key' => $antiXss->xss_clean($tfa_secret)
], [
'id[=]' => $userinfo['id']
]);

**Comment by locus313** [comment]
I tested the latest master and i am now able to scan the qr code and use the manual entry just fine. But when i tested the code for inserting into the database. That did not work. But since i saw the $tfa_key was now working for manual entry in Google Authenticator . just tried inserting it directly. (since it seems like its base32 encoded already) Doing this worked. Just for reference here is exactly what i used:

```
database::$auth->update('account', [
    'token_key' => $tfa_key
], [
    'id[=]' => $userinfo['id']
]);
```

**Comment by masterking32** [comment]
Yes, It's done xD
Thank you ❤️
