### ISSUE TITLE
Site doesn't display correctly

### ISSUE THREAD

**Issue by gr33k** [masterking32/WoWSimpleRegistration#32]
Hi - I'm using nginx and php-fpm to host this code, and I don't seem to be able to get it to display correctly.

**Nginx Info:**
nginx version: nginx/1.18.0

**PHP Info:**
PHP 7.3.23 (cli) (built: Sep 29 2020 08:33:03) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.23, Copyright (c) 1999-2018, by Zend Technologies

Basic PHP configuration - am I missing something?

```
  location / {
    try_files $uri $uri/ /index.php;
  }

  location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        try_files $uri =404;
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
	fastcgi_index index.php;
	include fastcgi.conf;
  }
```
I have all dependencies as far as I can tell (using Fedora 31 on this server) that are listed in the requirements. Is there one that would cause the site to load like plain HTML vs nice PHP layout in screenshots (i.e. advanced theme)?

This is what it looks like:
<img width="1440" alt="Screen Shot 2020-10-29 at 5 26 07 PM" src="https://user-images.githubusercontent.com/5171932/97646072-eb534f00-1a0b-11eb-9d36-eb4161e9f066.png">

Any suggestions are appreciated - ty

**Comment by masterking32** [comment]
Its about base_url in config file.
https://github.com/masterking32/WoWSimpleRegistration/blob/master/application/config/config.php.sample#L17

**Comment by gr33k** [comment]
Thanks @masterking32 !!! That was exactly it - I had to explicitly write in https://myurl.com - I just had myurl.com in there. 

Many Thanks! 👍
