### ISSUE TITLE
unable to create new account when activate HCaptcha or Captchat

### ISSUE THREAD

**Issue by Ryu1254** [masterking32/WoWSimpleRegistration#34]
Hello, 

I am unable to create a new account or reset password when activate the HCaptchat
I always got error: HCaptcha is not valid i already verified with the image identification.
in the php log error, i got this message:

[02-Jan-2021 23:02:53 America/Montreal] PHP Notice:  Trying to get property 'success' of non-object in C:\WoWSimpleRegistration\application\include\functions.php on line 207

I use php version 7.4.1x64TS with apache 2.4 on windows
with all the module require activated.

if i deactivate any captchat, then the account would create properly. this error appear as soon as i active any Captchat option
Any idea what causing this?

**Comment by kaneit** [comment]
I’m unable to reproduce such issue at the moment.
But I’ll happily try my best to help.

I’ll have a look later on today.

Please could you double check that your public key and secret are correctly
entered.

The steps I will reproduce is as follows.

Remove hcaptcha from config, remove domain from hcaptcha. And recreate to
generate a fresh public and secret key for domain. And and reupload a fresh
pull from GitHub.

**Comment by kaneit** [comment]
Baring in mind I do use a webhost. So that may possibly be the issue
perhaps?

**Comment by Ryu1254** [comment]
I recreate a new hcapchat site with new sitekey
but the secrete key, i cannot change it. i don't see any option..
still got the error. there must be something i miss.

the only thing different, is i host my self the web server..

**Comment by Ryu1254** [comment]
attached are httpd.conf, php.ini and the config file for WoWsimpleRegistration

i did try another test from scratch, using only Captchat. i still got the error "Captcha is required." even i type the key correctly..
[php.ini.txt](https://github.com/masterking32/WoWSimpleRegistration/files/5761220/php.ini.txt)
[httpd.conf.txt](https://github.com/masterking32/WoWSimpleRegistration/files/5761221/httpd.conf.txt)
[config.php.txt](https://github.com/masterking32/WoWSimpleRegistration/files/5761222/config.php.txt)

hope this can help.

**Comment by kaneit** [comment]
From looking at your php.uni
Soap module is disabled.

I’ll load up a xampp sometime today,
And I’ll see if I run into the same problem.

Are you using a dynamic DNS such as no-ip?
When putting your details in to hcaptcha?

**Comment by Ryu1254** [comment]
yes. i disable Soap, should i enable that?? i dont use bnet server or mfa.
i use my own domain name in the setting detail in Hostname

**Comment by kaneit** [comment]
If you read the config carefully it says which extensions need to be
enabled.
GMP, GD2, SOAP, cURL.

Definitely double check and read the config for this script very carefully.

I know SOAP is used to create accounts, but it says something about having
soap disabled in the config to allow reset of passwords.

¯\_(ツ)_/¯

I had similar issues with it myself.
A lot needs a bit of rewording and translating for emails etc and the
formatting needs to be corrected a bit within the script.

**Comment by DJBoxer** [comment]
> yes. i disable Soap, should i enable that?? i dont use bnet server or mfa.
> i use my own domain name in the setting detail in Hostname

Soap has nothing to do with your issue, its used for registering sending items in game thru console etc. Also to which you need to create a user for console access. 
Depending on your source code each emulator uses different methods for account creation, hence why you have those options and its the same with password changing each code is different i.e TC, AC, mangos etc.

I personally only used recaptchav2, so my thoughts on this would be incorrect details. 

Are you using correct domain name? such as "example.com"  (It should NOT contain http:// or https://) 

Also does the domain exist?

Is the Site and Secret key entered correctly? 

If your wishing to make your server public DON`T be using Xampp its intended purpose is for development not Production.
as the security is not the best unless you change a few things but this has nothing to do with your issue just bit of advice.

**Comment by Ryu1254** [comment]
Yes my domain name are correctly setup in hcaptcha , i did not includ any http:// nor https:// in the host name.
the site is reachable from any computer.

I dont use Xampp, i have it own apache server and it own mysql server.

i dont think it's the hcaptcha sit setting. or key. because i am able to resolve it.. probably.. a silly config in my httpd.conf or php.ini block something..

**Comment by Ryu1254** [comment]
ok i did another test. i installed xamp, using only captcha and try to create an account. it does working, that i coudnt with my regular apache setup. so now i have to dig to see what config in my my httpd.conf and php.ini causing this issues. keep you post.

thanks

**Comment by Ryu1254** [comment]
found the problem. after doing a lot of try and error by comparing xamp php.ini and mine.
here what cause the issues, in php.ini, I need to set this:
To use only the captcha, I simply need to activate the 
session.use_cookies = 1

To use the hcaptcha, I also need to add the follow line in the php.ini:

[openssl]
openssl.cafile="C:\Program Files\Apache Software Foundation\Apache24\bin\curl-ca-bundle.crt"

Now my problem are solved.

Thank everyone for the help. 
by the way, the site is very beautiful, thank you very much.
