### ISSUE TITLE
Add Korean Language

### ISSUE THREAD

**Issue by KOREAFTP** [masterking32/WoWSimpleRegistration#35]
Thanks for sharing a good website.
I edited the configuration file for Korean
Add files plase

File Name : korean.php

$language['lang'] = 'korean';
$language['custom_css'] = '';
$language['tpl_light_custom_css'] = '';
$language['tpl_advance_custom_css'] = '';
$language['tpl_icecrown_custom_css'] = '';
$language['tpl_kaelthas_custom_css'] = '';
$language['tpl_battleforazeroth_custom_css'] = '';

$language['welcome_to'] = '환영 합니다.';
$language['welcome_message'] = '서버에 오신 것을 환영합니다. 지금 가입하세요.';
$language['get_started'] = '시 작 하 기';
$language['home'] = '홈 화 면';
$language['about'] = '서버에 관하여';
$language['how_to_connect'] = '접 속 방 법';
$language['register'] = '회 원 가 입';
$language['server_status'] = '서 버 상 태';
$language['contact'] = '연 락 하 기';
$language['server_information'] = '서 버 정 보';
$language['server_type'] = '서 버 타 입';
$language['server_uptime'] = '서버 구동시간';
$language['xp_rate'] = '경험치 배율';
$language['drop_rate'] = '드랍 배율';
$language['start_level'] = '시작 레벨';
$language['max_level'] = '최대 레벨';
$language['fixed_spells'] = '스펠 수정사함';
$language['fixed_dungeons'] = '던전 수정사항';
$language['fixed_instances'] = '인던 수정사항';
$language['edit_on'] = '편집 가능';
$language['server_address'] = '서 버 주 소';
$language['realmlist'] = '렐름리스트';
$language['create_account'] = '계정생성';
$language['create_account_tip1'] = '먼저 계정을 생성해야 합니다. 이 계정은 웹페이지 로그인에 사용됩니다. 계정생성 페이지를 열려면 "회원가입"을 클릭하세요.';
$language['download_game'] = '클라이언트 다운로드';
$language['create_account_tip2'] = '월드 오브 워크래프트를 다운로드 하십시오. Windows, Mac 을 지원합니다. 현재 버전은'. get_config('game_version').'입니다.';
$language['setup_game'] = '게임 설치';
$language['create_account_tip3'] = '게임이 설치된 디렉토리를 엽니다."World of Warcraft\" "Data" 라는 폴더를 연 다음 "koKR" 폴더로 이동합니다. "realmlist.wtf" 파일을 메모장으로 엽니다.';
$language['change_server_address'] = '서버 주소 변경';
$language['create_account_tip4'] = '모든 텍스트를 지우고 다음으로 변경하세요.';
$language['server_rules'] = '서버규칙';
$language['read_before_register'] = '등록하기 전에 읽으십시오';
$language['read_our_rules'] = '서버 규칙에 대하여 숙지해주세요';
$language['rule'] = '서버규칙';
$language['create_new_game_account'] = '새로운 계정 생성';
$language['email'] = '이메일주소';
$language['username'] = '사용자ID';
$language['password'] = '패스워드';
$language['retype_password'] = '패스워드 확인';
$language['captcha'] = '보안문구(아래문자 입력)';
$language['change_password'] = '비밀번호 변경';
$language['restore_password'] = '비밀번호 복구';
$language['vote_for_us'] = '서버 투표하기';
$language['two_factor_authentication'] = '2단계 인증하기';
$language['two_factor_authentication_tip1'] = 'Google Authenticator. 설치하기';
$language['two_factor_authentication_enable'] = '2FA 활성화';
$language['close'] = '닫 기';
$language['vote'] = '투표';
$language['old_password'] = '이전 비밀번호';
$language['online_players'] = '온라인 플레이어';
$language['online_players_msg1'] = '최대 49명만 표시 - 현재 온라인 플레이어';
$language['online_players_msg2'] = '현재 게임중인 플레이어가 없습니다.';
$language['name'] = '이름';
$language['race'] = '종족';
$language['class'] = '클래스';
$language['level'] = '레벨';
$language['top_players'] = '상위 플레이어';
$language['play_time'] = '게임 플레이 시간';
$language['killers'] = '킬 현황';
$language['kills'] = '죽인 수';
$language['honor_points'] = '명예 포인트';
$language['honor_level'] = '명예 레벨';
$language['arena_points'] = '아레나 포인트';
$language['arena_teams'] = '아레나 팀';
$language['rank'] = '랭킹';
$language['rating'] = '등급';
$language['captain_name'] = '캡틴 이름';
$language['frequently_questions'] = '자주 묻는 질물';
$language['question'] = '질문';
$language['answer'] = '답변';
$language['location'] = '위치';
$language['call'] = '호출하기';
$language['restore_account_password'] = '비밀번호 초기화';
$language['about_server'] = '서버에 대하여';
$language['game_version'] = '게임 버전';
$language['server_patch'] = '서버 패치';
$language['download'] = '클라이언트 다운로드';

$language['use_valid_email'] = '이메일에 유효한 주소를 사용하세요';
$language['use_valid_username'] = '사용자 ID에 유효한 문자를 입력하세요';
$language['old_password_not_valid'] = '이전 비밀번호가 틀렸습니다.';
$language['passwords_not_equal'] = '비밀번호가 같지 않습니다.';
$language['passwords_length'] = '비밀번호 문자 길이가 유효하지 않습니다.';
$language['username_length'] = '사용자 ID 문자 길이가 유효하지 않습니다.';
$language['username_or_email_exists'] = '사용자 ID 또는 이메일이 이미 존재합니다.';
$language['email_exists'] = '이미 사용중인 이메일';
$language['username_exists'] = '이미 사용중인 ID';
$language['account_created'] = '새로운 계정이 생성되었습니다.';
$language['error_try_again'] = '오류!! 다시 시도하세요.';
$language['password_changed'] = '비밀번호가 변경되었습니다.';
$language['email_not_correct'] = '이메일 주소가 올바르지 않습니다.';
$language['username_not_correct'] = '사용자 ID가 올바르지 않습니다.';
$language['check_your_email'] = '이메일을 확인해 주세요.(스팸, 정크메일로 수신될 수 있습니다.)';
$language['account_is_not_valid'] = '계정이 유효하지 않습니다.';
$language['vote_site_not_valid'] = '투표 사이트가 유효하지 않습니다.';
$language['you_already_voted'] = '이미 투표 하셨습니다.';
$language['captcha_not_valid'] = '보안문자가 틀렸습니다.';
$language['hcaptcha_not_valid'] = '보안문자가(HCaptcha) 틀렸습니다.';
$language['recaptcha_not_valid'] = '보안문자가(ReCaptcha) 틀렸습니다.';
$language['captcha_required'] = '보안문자가(Captcha) 필요합니다.';

**Comment by DuelistRag3** [comment]
You should simply create a pull request

**Comment by masterking32** [comment]
Ok, I will make a commit ...
