### ISSUE TITLE
Images not displaying, templates not loading

### ISSUE THREAD

**Issue by darkzen-zz** [masterking32/WoWSimpleRegistration#38]
Recently installed this site to use for registrations and I seem to have it connected to my Wow server, but I have issues with getting this site to display any images, or even formatting.
Site is being hosted on a Debian 10 (Buster) Linux VM locally. 
Using 
PHP 7.3.19-1~deb10u1
Apache/2.4.38 (Debian)
PHP7.3-common 

I have enabled the following in php.ini

> extension=gd2
> extension=gmp
> extension=mbstring
> extension=pdo_firebird
> extension=pdo_mysql
> extension=pdo_oci
> extension=pdo_odbc
> extension=snmp
> extension=soap

The site looks like this
![wowweb1](https://user-images.githubusercontent.com/6239648/105786149-80ea7600-5f4a-11eb-810f-0e2c51e3331c.JPG)

Verified the URL in settings, and also tried different templates, they all do the same thing.

**Comment by DJBoxer** [comment]
https://github.com/masterking32/WoWSimpleRegistration/issues/32

**Comment by darkzen-zz** [comment]
@DJBoxer Already went through this thread #32  Not the same issue.

**Comment by masterking32** [comment]
Hey, @darkzen-zz Its same!
Open the website with same address in `baseurl` (Check `http` and `https`)

**Comment by darkzen-zz** [comment]
Seems to be an issue with my proxy. I can get to it locally via IP (when I put the IP in there) however same thing with the actual URL. I will do some more research and let you know. 
I am curious why the site structure is dependent on the domain name and not relative path?

**Comment by masterking32** [comment]
I will remove it later.
