### ISSUE TITLE
Registration issues

### ISSUE THREAD

**Issue by wolone** [masterking32/WoWSimpleRegistration#39]
[]([![yVhkC9.png](https://s3.ax1x.com/2021/02/01/yVhkC9.png)](https://imgchr.com/i/yVhkC9))
Page reality normal

Registration also indicates success

The database has no registration information

**Comment by wolone** [comment]
[![yVhkC9.png](https://s3.ax1x.com/2021/02/01/yVhkC9.png)](https://imgchr.com/i/yVhkC9)

**Comment by masterking32** [comment]
Hey, Check your config, Enable SPR6 if you are using the last version of the TC.

**Comment by milestorme** [comment]
I had this issue using cmangos with srp6 enabled , shows success but no account data is added to the realmd database

**Comment by masterking32** [comment]
Can you share Auth database of Cmangos, Try register with enable debug mode.

**Comment by milestorme** [comment]
no errors it says "Your account has been created" only it doesn't insert anything into realmd , heres the table [https://github.com/milestorme/mangos-tbc/blob/master/sql/base/realmd.sql](url)

**Comment by caicaicai** [comment]
replace salt and verifier with s and v in user.php

**Comment by caicaicai** [comment]
but ... the salt and the verifier will calc to  some garbled .
![Uploading WX20210218-092210@2x.png…]()

**Comment by caicaicai** [comment]
<img width="1093" alt="WX20210218-092210@2x" src="https://user-images.githubusercontent.com/3754009/108290220-ed176d00-71ca-11eb-9491-9b966cf35e27.png">

**Comment by caicaicai** [comment]
I gave up, now I use soap to register, and it works great.

**Comment by CraftedRO** [comment]
Seems like it dosen't work on latest trinitycore #2f9e386 (18.02.2021) too , even with srp6 enabled it show this error :
[Error.txt](https://github.com/masterking32/WoWSimpleRegistration/files/6004276/Error.txt)
Without srp6 it does show successfull but the database is empty .

**Comment by caicaicai** [comment]
your error txt show that you should install gmp php extension.

**Comment by CraftedRO** [comment]
After I enabled gmp (by uncomment ;extension=gmp in php.ini) it works well .

**Comment by masterking32** [comment]
Change https://github.com/masterking32/WoWSimpleRegistration/blob/master/application/config/config.php.sample#L60 to CMangos, then try to enable SPR6 and send feedback.

**Comment by caicaicai** [comment]
still not work ,
My php environment is docker：
`
FROM php:7.4-apache

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libwebp-dev \
    libjpeg62-turbo-dev \
    libpng-dev libxpm-dev \
    libfreetype6-dev libgmp-dev libpng-dev  libzip-dev libxml2-dev vim --allow-unauthenticated
RUN docker-php-ext-configure gd  --with-jpeg  --with-freetype 
RUN docker-php-ext-install gd gmp pdo_mysql mysqli soap zip


ADD . /var/www/html/
`
$config['server_core'] = 5;
$config['srp6_support'] = true; 

regist result：
`
INSERT INTO `account` (`id`, `username`, `gmlevel`, `sessionkey`, `v`, `s`, `email`, `joindate`, `lockedIp`, `failed_logins`, `locked`, `active_realm_id`, `expansion`, `mutetime`, `locale`, `token`, `restore_key`)
VALUES
	(4, 'TEST111111', 0, NULL, '??Bŏ\r0*?8l??=??>R8?hh?{???8?w', '??\0p?L??ȚڏA(????wp?2?M??*e', 'ADMIN123123@TEST.COM', '2021-02-20 14:07:32', '0.0.0.0', 0, 0, 0, 2, 0, '', NULL, '1');

`

**Comment by caicaicai** [comment]
Maybe the gmp what I installed is wrong?

**Comment by caicaicai** [comment]
the v and s should be something pure numbers and letters .but what I got is some unreadable stuff.

**Comment by masterking32** [comment]
> 
> 
> the v and s should be something pure numbers and letters .but what I got is some unreadable stuff.

Can you try now?

**Comment by caicaicai** [comment]
Really awesome! now it works perfectly, thank you!
