### ISSUE TITLE
No images or template

### ISSUE THREAD

**Issue by Toomuchsugar** [masterking32/WoWSimpleRegistration#44]
![image](https://user-images.githubusercontent.com/20241741/112534398-42b1dd00-8d68-11eb-9c85-d8ac9c53a869.png)

Not seeing images, is there a solution or work around for this?

**Comment by masterking32** [comment]
Hey, Please read the comments in config.php file.
https://github.com/masterking32/WoWSimpleRegistration/blob/master/application/config/config.php.sample#L20
