### ISSUE TITLE
Not working for the newest version of AzerothCore

### ISSUE THREAD

**Issue by lach3v** [masterking32/WoWSimpleRegistration#45]
As the title says, currently the page is not working for the newest version of AzerothCore. The core got updated and apparently that introduced some new implementations to the account system.

Currently if you try to register an account with this page, while using AzerothCore, you will get the green message "Your account has been created.", but in reality it is not.

**Comment by masterking32** [comment]
Hey, enable SPR6 for the last versions of AC.
