### ISSUE TITLE
Fail Register with latest AzerothCore

### ISSUE THREAD

**Issue by betayi** [masterking32/WoWSimpleRegistration#46]
**Describe the bug**
Make sure you are enabled debug_mode in the config file.

Displayed "Created"
But no account create in database

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Server core: [e.g. TrinityCore]
 - Game version: [e.g 3.3.5]
 - PHP version: [e.g 7.1.0]

**Additional context**

**Comment by masterking32** [comment]
Hey, enable SPR6 for the last versions of AC.
