### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by kicho** [masterking32/WoWSimpleRegistration#5]
I get this error:

host Localhost cant proccess your current request
HTTP ERROR 500

**Comment by kicho** [comment]
with debug its


Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in C:\xampp\htdocs\wow\application\vendor\catfan\medoo\src\Medoo.php:323 Stack trace: #0 C:\xampp\htdocs\wow\application\include\database.php(26): Medoo\Medoo->__construct(Array) #1 C:\xampp\htdocs\wow\application\loader.php(49): database::db_connect() #2 C:\xampp\htdocs\wow\index.php(33): require_once('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\wow\application\vendor\catfan\medoo\src\Medoo.php on line 323

**Comment by masterking32** [comment]
Check this: https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to
