### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by cadafy** [masterking32/WoWSimpleRegistration#52]
**Describe the bug**
Make sure you are enabled debug_mode in the config file.

**To Reproduce**
1. Go to 'up to page'

**Desktop (please complete the following information):**
 - OS: [windows 10
 - Server core: AzerothCore
 - Game version: [8.3.7]
 - PHP version: [7.4
 - Browser chrome, eage]

![error1](https://user-images.githubusercontent.com/1677095/128792949-f6571710-7bba-48cc-868b-38c50d31564b.png)

https://imgbox.com/6fbRWaAY

**Comment by masterking32** [comment]
hi, that's about your MySQL connection information (Like username, password)

**Comment by cadafy** [comment]
greetings I am using a hosting called HOSTINGER. I have tried everything

**Comment by cadafy** [comment]
solved

**Comment by SaidKing** [comment]
> solved, Thaks you for help


What is the solution to the problem?
