### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by Vanheden** [masterking32/WoWSimpleRegistration#55]
**Describe the bug**
Changing password don't work, new password says the password is not valid when trying to change it.
You can still login to the game with it.

**To Reproduce**
1. Recover Password
2. Try change password

**Expected behavior**
Should change password

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Server core: vMangos
 - Game version: 1.12.1
 - PHP version: 7.4
 - Browser: Chrome

**Comment by masterking32** [comment]
Idk about vMangos!
If that uses SPR6, you must enable it!

**Comment by Vanheden** [comment]
Hello, SRP6 is enabled.

**Comment by masterking32** [comment]
Share your vMangos repo and if you are using SOAP for register .... change the password not working make sure that feature is disabled.

**Comment by JumpingY** [comment]
I had the same problem，I use Light'hope Vanilla Reapck V21 and disable SOAP，I can receive the new password witch can login the game. but it said Invalid old password when I change the password in webpage
