### ISSUE TITLE
Creating passwords do not work properly

### ISSUE THREAD

**Issue by Mr-Deadbeat** [masterking32/WoWSimpleRegistration#57]
**Describe the bug**
when creating a test account for one of my test runs on your registration application
i added the account but the password got rejected does it count the max allowable password lengths that Wrath of the lich king client supports think it was 16 characters

also does it support extended Ascii just wondering since i used Keepassxc to create the password had to fiddle with the settings to find a working password with a complicated enough password for my standards ;) mixed special characters, numbers and so on for maximum entropy

**To Reproduce**
1. create account name
2. create the password test the most advanced password option from keepassxc "creates utter gibberish" for maximum entropy
3. click on create account
4. and it will give you error for failed creation of account not sure if the server core itself does not support
advanced passwords or if it's some oversight on your part either way thought i might give you a heads up on this issue
otherwise things work smoothly :) great work

btw server is not public it's just for my own use on my local network might open it up at a later date for friends and family

**Expected behavior**
created account without issues

**Screenshots**
have none

**Desktop (please complete the following information):**
 - OS: Ubuntu Mate 20.04.3
 - Server core: TrinityCore
 - Game version: 3.3.5a
 - PHP version: 7.4.3
 - Browser Chrome

**Additional context**
nothing more to add other than keep up the good work :)

**Comment by masterking32** [comment]
Actually, On the website, you can use any character for the password, but wow client cannot support everything.

**Comment by Mr-Deadbeat** [comment]
> Actually, On the website, you can use any character for the password, but wow client cannot support everything. The best way to secure the accounts is using 2fa.

yes i know but need to setup a web server to support 2fa which i have none atm ;)

the error i referred to during account creation was on the web server after everything was filled in including password i got the error message that in turn got me thinking maybe there are some character combos that are not taken into account ? as a test i created the same password trough the remote admin console and it accepted it so not sure what might be going on

just makes it a bit tedious to do things all over again if the password does get rejected ;)

**Comment by masterking32** [comment]
Hey,
We didn't add any checks for password characters!
[Check this](https://github.com/masterking32/WoWSimpleRegistration/blob/7034c221dff1ac4fdae43db9db67ce3bf9a28ca1/application/include/user.php#L179)
Maybe something is wrong with your web server.
