### ISSUE TITLE
Page blank

### ISSUE THREAD

**Issue by wolone** [masterking32/WoWSimpleRegistration#6]
[![GZHQ5F.png](https://s1.ax1x.com/2020/03/29/GZHQ5F.png)](https://imgchr.com/i/GZHQ5F)
[![GZHMUU.png](https://s1.ax1x.com/2020/03/29/GZHMUU.png)](https://imgchr.com/i/GZHMUU)
[![GZHKET.png](https://s1.ax1x.com/2020/03/29/GZHKET.png)](https://imgchr.com/i/GZHKET)

**Comment by masterking32** [comment]
Hi @wolone, can you share your web server, PHP and MySQL versions? (If you use software like XAMPP or WAMPP tell me)
