### ISSUE TITLE
AzerothCore registered account function is invalid

### ISSUE THREAD

**Issue by sw586** [masterking32/WoWSimpleRegistration#61]
**Describe the bug**
After registration, there is no account data in the database "account" table

**Expected behavior**
After completing the registration action, and WoWSimpleRegistration prompts: "Your account has been created." The mysql.account table should create account data
**Screenshots**

**Desktop (please complete the following information):**
  -OS: [windows10]
  -Server core: [azerothcore]
  -Core repository: [https://github.com/azerothcore/azerothcore-wotlk]
  -Game version: [3.3.5]
  -PHP version: [7.2.0]
  -Browser [chrome]

**Additional context**

**Comment by JarvanDing** [comment]
> Did you enable SPR6? Enable debug.

Is that SRP6?
Where is this configuration file? Web server or wow server profile?

**Comment by gr33k** [comment]
THIS WAS THE FIX! Thanks you :D 

All I had to do to make DB account creation work was set $config['srp6_support'] = true;
