### ISSUE TITLE
Registration with hcaptcha enabled fail with error message

### ISSUE THREAD

**Issue by hinamori2607** [masterking32/WoWSimpleRegistration#62]
Describe the bug :

Encounter registration error visible by enable debug option. I already enable gd int php....

1. Go to website url
2. Click on register
3. Fill with account email & password then resolve hcaptcha
4. See error : Fatal error: `Uncaught Error: Call to undefined function curl_init() in C:\srvwow\website\application\include\functions.php:212 Stack trace: #0 C:\srvwow\website\application\include\functions.php(256): validate_hcaptcha('XXXXXXXXX') #1 C:\srvwow\website\application\include\user.php(81): captcha_validation() #2 C:\srvwow\website\application\include\user.php(33): user::bnet_register() #3 C:\srvwow\website\index.php(34): user::post_handler() #4 {main} thrown in C:\srvwow\website\application\include\functions.php on line 212`

Expected behavior :
Create account

Desktop :
 - OS: Windows server 2016
 - Server core: TrinityCore (SPP legion)
 - Game version: [e.g 3.3.5]
 - PHP version: 7
 - Browser Firefox

php.ini :

```
;extension=php_bz2.dll
extension=php_curl.dll
;extension=php_fileinfo.dll
extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
extension=php_intl.dll
extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
;extension=php_exif.dll      ; Must be after mbstring as it depends on it
extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
;extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_shmop.dll
```
php error log :

`PHP Warning:  PHP Startup: Unable to load dynamic library 'php_curl.dll' (tried: ../php7/ext\\php_curl.dll (Le module sp\xef\xbf\xbdcifi\xef\xbf\xbd est introuvable.), ../php7/ext\\php_php_curl.dll.dll (Le module sp\xef\xbf\xbdcifi\xef\xbf\xbd est introuvable.)) in Unknown on line 0

`

**Comment by masterking32** [comment]
Hi, 
This is not related to the project.
https://stackoverflow.com/questions/32718133/php-warning-php-startup-unable-to-load-dynamic-library-php-curl-dll-impossibil
https://serverfault.com/questions/279033/curl-extension-not-working-php-warning-php-startup-unable-to-load-dynamic-li

**Comment by hinamori2607** [comment]
Yep this is true.

I resolved this issue by hosting my portal on another server.

Sorry for inconvenience

**Comment by hinamori2607** [comment]
Thanks for your quick reply
