### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by DaronNX** [masterking32/WoWSimpleRegistration#64]
**Describe the bug**
So after configuring everything that I needed for registration to work, I tried registering accounts and it says your account has been created but the database has no new accounts. I'm not getting any errors and the wow server seems to be working just fine.

**To Reproduce**
1. Install the website
2. Configure settings
3. Attempt to create account

**Expected behavior**
The account should end up inserted into the DB

**Screenshots**
https://i.imgur.com/NdfVpRA.png

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Server core: Azeroth
 - Core repository: https://github.com/azerothcore/azerothcore-wotlk
 - Game version: 3.3.5
 - PHP version: 7.4
 - Browser: Opera(chromium)

**Additional context**
If I enable picture captcha it either says captcha is required or captcha failed when everything is right.
I'm also running it on a 4 node load balanced website with round robin balancing.

**Comment by masterking32** [comment]
Hey, Did you enable SPR6 on the config file?
