### ISSUE TITLE
Can not change password

### ISSUE THREAD

**Issue by JumpingY** [masterking32/WoWSimpleRegistration#73]
Share your vMangos repo and if you are using SOAP for register .... change the password not working make sure that feature is disabled.

_Originally posted by @masterking32 in https://github.com/masterking32/WoWSimpleRegistration/issues/55#issuecomment-933717411_

I had the same problem，I use Light's Hope Vanilla Reapck V21 and disable SOAP，I can receive the new password which can login the game. but it said Invalid old password when I change the password in webpage,
It may be caused by [this change](https://github.com/vmangos/core/commit/bbebe20779df9edeec552048fa839553b5de6c28)

**Comment by masterking32** [comment]
Change 
https://github.com/masterking32/WoWSimpleRegistration/blob/308a93bbac0ffc6b1b50ad49804c903926139328/application/config/config.php.sample#L76
to 5 and  enable:
https://github.com/masterking32/WoWSimpleRegistration/blob/308a93bbac0ffc6b1b50ad49804c903926139328/application/config/config.php.sample#L91
