### ISSUE TITLE
Captcha Builder Deprecated

### ISSUE THREAD

**Issue by StonedCookieGaming** [masterking32/WoWSimpleRegistration#77]
**Describe the bug**
I am getting the following errors:

Deprecated: Creation of dynamic property Gregwar\Captcha\CaptchaBuilder::$background is deprecated in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 430 

Deprecated: Implicit conversion from float 23.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 31.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 42.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 32.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 62.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 36.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 86.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 34.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 106.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

Deprecated: Implicit conversion from float 36.5 to int loses precision in /home/site/wwwroot/application/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php on line 365

**To Reproduce**
1. Set up your website
2. Enable debug mode
3. Go to your website in your browser
4. Observe the errors

**Expected behavior**
It shouldn't flash this error and the website should load properly.

**Screenshots**
![Screenshot 2023-05-28 234852](https://github.com/masterking32/WoWSimpleRegistration/assets/12970601/4cd407e8-fd26-4b93-84a9-4e084acf3696)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Server core: TrinityCore
 - Core repository: https://github.com/TrinityCore/TrinityCore
 - Game version: 10.1.0
 - PHP version: 8.2
 - Browser: Microsoft Edge

**Additional context**
N/A

**Comment by masterking32** [comment]
Solved.
