### ISSUE TITLE
no image

### ISSUE THREAD

**Issue by Bobbbe** [masterking32/WoWSimpleRegistration#83]
Hello :) first, i want told you a big big thx for your good job, is very apreciate.
![configip](https://github.com/masterking32/WoWSimpleRegistration/assets/42454593/b6a96785-d912-4325-8216-b60ce81ee87f)
![doubleip](https://github.com/masterking32/WoWSimpleRegistration/assets/42454593/18df5be0-25e6-4254-b7c9-7335c7762578)
I installed the latest version of the "Simple Register" and since then, the page loads but without the images and video. I registered the same address that I have always used since everything was working fine before the update. I have a screen showing the site on the left and the inspector on the right. we can see that the ip seems to be duplicated. I don't know where it can come from.

**Comment by masterking32** [comment]
https://github.com/masterking32/WoWSimpleRegistration/blob/498f5be282ddf0fb81de7ff3b90497b16236c2af/application/config/config.php.sample#L20C4-L20C143
check this, you need to add `http://`

**Comment by JonathanAkaJD** [comment]
I use ./ by doing that it supports http and https
