### ISSUE TITLE
Vote sites quality of life suggestion

### ISSUE THREAD

**Issue by Robert606** [masterking32/WoWSimpleRegistration#9]
Hello,

First of all i wanna say thank you for the amazing Simple registration page.

However i have 1 suggestion. Could you make the vote sites open in a new tab instead when clicking the vote sites?
It's a little hectic to open the vote site, having to go back to the site, scroll down and rinse and repeat.

Other than that its awesome. Thank you!

**Comment by masterking32** [comment]
Done <3

**Comment by Robert606** [comment]
Thank you.

Found another issue though, upon clicking the vote site, it opens in a new window, but actually the website itself just re-opens. (the vote site doesn't open in the new window)

Could you look into that please? much appreciated.
